import type { Sot } from './types'

export const defaultSot: Sot = {
  brand: {
    productName: 'NT Brokerio Asistentas',
    edition: 'Spin-off Nr. 7',
    positioning: 'Sukurk profesionalų skelbimą, klientų atsakymą ar derybų strategiją per 60 sek. su AI pagalba.',
  },
  copy: {
    promptAnatomyUrl: 'https://www.promptanatomy.app/',
    heroTitle: 'NT Brokerio Asistentas',
    heroSubtitle: 'Sukurk profesionalų skelbimą, klientų atsakymą ar derybų strategiją per 60 sek. su AI pagalba.',
    heroCtaPrimary: 'Generuoti',
    heroCtaSecondary: 'Šablonų biblioteka',
    heroCtaMeta: 'Sutaupyk iki 5 val. per savaitę. Sukurta brokeriams.',
    badge: 'NT Brokerio Asistentas',
    loadingLabel: 'Kraunama...',
    copyErrorLabel: 'Klaida:',
    copyRetryLabel: 'Bandyti dar kartą',
    copySuccess: 'Nukopijuota',
    copyFailed: 'Kopijuoti nepavyko',
    btnCopy: 'Kopijuoti',
    rulesAriaLabel: 'Ką gausite',
    themeToggleLabelLight: 'Perjungti į tamsų režimą',
    themeToggleLabelDark: 'Perjungti į šviesų režimą',
    promptAnatomyLinkText: 'Promptų anatomija →',
    promptAnatomyAriaLabel: 'Promptų anatomija – atidaroma naujame lange',
    inputBlockLabel: 'INPUT (užpildyta)',
    footerDebugLabel: 'Tema: {{theme}}. SOT pakrautas – režimai, copy ir spalvos valdomi iš config/sot.json.',
    modalTemplatesTitle: 'Šablonų biblioteka',
    btnUse: 'Naudoti',
    btnClose: 'Uždaryti',
    selectPlaceholder: 'Pasirinkite',
    loadError404: 'Config nerastas (404). Naudojamas numatytasis nustatymas.',
    loadErrorGeneric: 'Nepavyko užkrauti konfigūracijos. Naudojamas numatytasis nustatymas.',
    activeModeLabel: 'Aktyvus režimas:',
    contactEmail: 'info@promptanatomy.app',
    footerContactLabel: 'Kontaktai:',
    footerCredit: 'Spin-off Nr. 7 iš Promptų anatomijos.',
    firstStepHint: 'Pasirink režimą ir užpildyk bent 1–2 laukus – rezultatas priklausys nuo įvesties.',
    outputDefaultTitle: 'Tavo sugeneruotas AI prompt',
    outputDefaultHint: 'Galite redaguoti tekstą čia prieš kopijuojant. Nukopijuok ir įklijuok į ChatGPT arba Claude.',
    onboardingSteps: [
      'Pasirink režimą viršuje',
      'Užpildyk pagrindinius laukus',
      'Spustelk mygtuką – gausite AI prompt',
      'Kopijuok prompt ir įklijuok į ChatGPT',
    ],
    fieldProgressLabel: '{{filled}}/{{total}} laukų užpildyta',
    baseFieldsGroupLabel: 'Objekto duomenys',
    rulesTitle: 'Ką gausite',
    emptyGenerateHint: 'Pridėk bent lokaciją ir kainą – rezultatas bus tikslesnis.',
    aiToolLinksLabel: 'Nori išbandyti užklausą? Pasirink įrankį:',
    charCountLabel: 'Simbolių: {{count}}',
    operationCenterLabel: 'NT brokerio centras',
    operationCenterSubLabel: 'Pasirink režimą, užpildyk laukus ir gauk paruoštą užklausą',
    whatsappUrl: 'https://chat.whatsapp.com/It49fzTl1n90huRCoWWkwu?mode=gi_t',
    whatsappLabel: 'Prisijungti prie WhatsApp grupės',
    skipToContentLabel: 'Pereiti prie turinio',
    footerTagline: 'Promptas sukurtas. Nori daugiau?',
    footerCopyright: '© 2026 Promptų anatomija. Visos teisės saugomos.',
    communityTitle: 'Nori daugiau?\nPrisijunk prie WhatsApp grupės.',
    communitySubtitle: 'Bendros diskusijos, patarimai ir naujienos apie NT rinką ir AI įrankius.',
    communityCtaPrimary: 'Prisijungti prie WhatsApp grupės',
    communityCtaSecondary: 'Promptų anatomija →',
    privacyLabel: 'Privatumas',
    privacyUrl: '',
    outputBadgeLabel: 'SUGENERUOTA UŽKLAUSA',
    outputCopyCtaLabel: 'KOPIJUOTI UŽKLAUSĄ',
    noTemplateHint: 'Šiam režimui šablonas nepasirinktas. Pasirinkite šabloną iš bibliotekos žemiau.',
    noTemplateCtaLabel: 'Peržiūrėti šablonus',
    templatesSectionTitle: 'Šablonų biblioteka',
    templatesExpandLabel: 'Rodyti pilną šabloną',
    templatesCollapseLabel: 'Sutraukti',
    sessionsTitle: 'Sesijos',
    sessionsSaveLabel: 'Išsaugoti',
    sessionsDeleteAllLabel: 'Ištrinti sesijas',
    sessionsEmptyLabel: 'Nėra išsaugotų sesijų.',
    sessionDeleteLabel: 'Ištrinti',
    sessionCopyLabel: 'Kopijuoti',
    sessionRestoreLabel: 'Atkurti',
    sessionsFullLabel: 'Sesijos pilnos (maks. 20). Ištrinkite senesnes.',
    recommendedStartLabel: 'Rekomenduojama pradžia',
    copySuccessCtaPrefix: 'Nori daugiau?',
    outputLearnMorePrefix: 'Sužinok daugiau apie promptus:',
    aiToolLinksPromptAnatomyLabel: 'Mokykis promptų anatomijos →',
    templatesSourcePrefix: 'Šablonai iš ',
  },
  showDebugInFooter: false,
  modesOrder: ['OBJEKTAS', 'SKELBIMAS', 'KOMUNIKACIJA', 'DERYBOS', 'ANALIZE'],
  modes: {
    OBJEKTAS: {
      id: 'objektas',
      label: 'Objektas',
      desc: 'Objekto analizė ir vertė',
      longDesc: 'Analizuok NT objekto vertę, stipriąsias puses ir tikslinę auditoriją. AI parengs objekto vertinimo prompt.',
      ctaLabel: 'Analizuoti objektą',
      outputTitle: 'Objekto analizės prompt',
      outputHint: 'Kopijuok šį prompt ir įklijuok į ChatGPT – gausite objekto analizę su vertės argumentais.',
      accentColor: '#0891b2',
      formId: 'form-objektas',
      icon: 'building-2',
      fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas'],
      fieldGroups: [
        { label: 'Objekto duomenys', fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas'] },
      ],
    },
    SKELBIMAS: {
      id: 'skelbimas',
      label: 'Skelbimas',
      desc: 'NT skelbimo kūrimas',
      longDesc: 'Sukurk profesionalų skelbimą NT portalams (Aruodas, skelbimai.lt) arba socialiniams tinklams. AI suformuos hook, USP ir CTA.',
      ctaLabel: 'Sukurti skelbimą',
      outputTitle: 'Skelbimo prompt',
      outputHint: 'Kopijuok šį prompt ir įklijuok į ChatGPT – gausite paruoštą skelbimo tekstą.',
      accentColor: '#2563eb',
      formId: 'form-skelbimas',
      icon: 'sparkles',
      libraryPromptId: 'skelbimas_nt',
      fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas', 'platforma', 'strategija', 'ilgis'],
      fieldGroups: [
        { label: 'Skelbimo nustatymai', fields: ['platforma', 'strategija', 'ilgis'] },
        { label: 'Objekto duomenys', fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas'], collapsible: true, defaultCollapsed: false },
      ],
    },
    KOMUNIKACIJA: {
      id: 'komunikacija',
      label: 'Komunikacija',
      desc: 'Klientų atsakymai',
      longDesc: 'Parengk profesionalų atsakymą klientui – pirkėjui ar pardavėjui. AI suformuos žinutę su vertės pasiūlymu ir CTA.',
      ctaLabel: 'Parengti atsakymą',
      outputTitle: 'Komunikacijos prompt',
      outputHint: 'Kopijuok šį prompt ir įklijuok į ChatGPT – gausite paruoštą atsakymą klientui.',
      accentColor: '#7c3aed',
      formId: 'form-komunikacija',
      icon: 'message-square',
      libraryPromptId: 'komunikacija_pirkėjas',
      fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas', 'klientoTipas', 'situacija', 'zinute', 'ctaTipas'],
      fieldGroups: [
        { label: 'Komunikacijos kontekstas', fields: ['klientoTipas', 'situacija', 'zinute', 'ctaTipas'] },
        { label: 'Objekto duomenys', fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas'], collapsible: true, defaultCollapsed: false },
      ],
    },
    DERYBOS: {
      id: 'derybos',
      label: 'Derybos',
      desc: 'Derybų strategija',
      longDesc: 'Parenk derybų strategiją ir argumentus – ginti kainą, ieškoti kompromiso ar uždaryti sandorį. AI suformuos argumentaciją.',
      ctaLabel: 'Parengti strategiją',
      outputTitle: 'Derybų prompt',
      outputHint: 'Kopijuok šį prompt ir įklijuok į ChatGPT – gausite derybų strategiją su argumentais.',
      accentColor: '#dc2626',
      formId: 'form-derybos',
      icon: 'handshake',
      libraryPromptId: 'derybu_strategija',
      fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas', 'siulomaKaina', 'kontekstas', 'derybuTikslas'],
      fieldGroups: [
        { label: 'Derybų kontekstas', fields: ['siulomaKaina', 'kontekstas', 'derybuTikslas'] },
        { label: 'Objekto duomenys', fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas'], collapsible: true, defaultCollapsed: false },
      ],
    },
    ANALIZE: {
      id: 'analize',
      label: 'Analizė',
      desc: 'Rinkos analizė ir turinys',
      longDesc: 'Sukurk ekspertinį NT rinkos turinį – apžvalgą, prognozę ar analizę nurodyta tema. AI suformuos struktūruotą turinį.',
      ctaLabel: 'Generuoti analizę',
      outputTitle: 'Analizės prompt',
      outputHint: 'Kopijuok šį prompt ir įklijuok į ChatGPT – gausite ekspertinį rinkos turinį.',
      accentColor: '#059669',
      formId: 'form-analize',
      icon: 'bar-chart-3',
      libraryPromptId: 'rinkos_analize',
      fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas', 'tema', 'turinioTipas'],
      fieldGroups: [
        { label: 'Analizės nustatymai', fields: ['tema', 'turinioTipas'] },
        { label: 'Objekto duomenys', fields: ['objektoTipas', 'lokacija', 'plotas', 'kambariai', 'kaina', 'bukle', 'statybosMetai', 'aukstas', 'sildymas', 'irengimas', 'privalumai', 'auditorija', 'tonas'], collapsible: true, defaultCollapsed: false },
      ],
    },
  },
  fieldMeta: {
    objektoTipas: { label: 'Objekto tipas', type: 'select', placeholder: 'Pasirinkite', options: ['Butas', 'Namas', 'Kotedžas', 'Komercinės patalpos', 'Sklypas', 'Garažas'], recommended: true },
    lokacija: { label: 'Lokacija / adresas', type: 'text', placeholder: 'Miestas, rajonas', recommended: true },
    plotas: {
      label: 'Plotas (m²)',
      type: 'select',
      placeholder: 'Pasirinkite',
      options: ['iki 50 m²', 'iki 75 m²', 'iki 100 m²', 'iki 150 m²', 'iki 200 m²', '200+ m²'],
    },
    kambariai: { label: 'Kambarių sk.', type: 'select', placeholder: 'Pasirinkite', options: ['1', '2', '3', '4', '5', '6+'] },
    kaina: {
      label: 'Kaina (€)',
      type: 'select',
      placeholder: 'Pasirinkite',
      options: ['iki 50 000 €', 'iki 75 000 €', 'iki 100 000 €', 'iki 150 000 €', 'iki 200 000 €', '200 000+ €'],
      recommended: true,
    },
    bukle: { label: 'Būklė', type: 'select', placeholder: 'Pasirinkite', options: ['Nauja statyba', 'Renovuotas', 'Geros būklės', 'Vidutinės būklės', 'Reikia remonto'] },
    statybosMetai: { label: 'Statybos metai', type: 'select', placeholder: 'Pasirinkite', options: ['Iki 1940', '1941–1960', '1961–1990', '1991–2000', '2001–2010', '2011–2020', '2021+'] },
    aukstas: { label: 'Aukštas', type: 'select', placeholder: 'Pasirinkite', options: ['1', '2', '3', '4', '5', '6–10', '10+', 'Palėpė'] },
    sildymas: { label: 'Šildymas', type: 'select', placeholder: 'Pasirinkite', options: ['Centrinis', 'Dujinis', 'Elektrinis', 'Kietojo kuro', 'Šilumos siurblys'] },
    irengimas: { label: 'Įrengimas', type: 'select', placeholder: 'Pasirinkite', options: ['Pilnai įrengtas', 'Dalinė apdaila', 'Neįrengtas'] },
    privalumai: { label: 'Privalumai', type: 'textarea', placeholder: 'USP, privalumai' },
    auditorija: { label: 'Auditorija', type: 'select', placeholder: 'Pasirinkite', options: ['Jauna šeima', 'Investuotojas', 'Pirmas būstas', 'Pensininkai', 'Verslininkai'] },
    tonas: { label: 'Tonas', type: 'select', placeholder: 'Pasirinkite', options: ['premium', 'neutralus', 'draugiškas'] },
    platforma: { label: 'Platforma', type: 'select', placeholder: 'Pasirinkite', options: ['Aruodas', 'Skelbimai.lt', 'Facebook', 'Instagram', 'LinkedIn'] },
    strategija: { label: 'Strategija', type: 'select', placeholder: 'Pasirinkite', options: ['Emocinis', 'Racionalus', 'Mišrus'] },
    ilgis: { label: 'Ilgis', type: 'select', placeholder: 'Pasirinkite', options: ['Trumpas', 'Vidutinis', 'Ilgas'] },
    klientoTipas: { label: 'Kliento tipas', type: 'select', placeholder: 'Pasirinkite', options: ['Pirkėjas', 'Pardavėjas', 'Nuomininkas'] },
    situacija: { label: 'Situacija', type: 'select', placeholder: 'Pasirinkite', options: ['Domisi kaina', 'Follow-up po apžiūros', 'Neatsako', 'Pasiūlymo teikimas', 'Pirmas kontaktas'] },
    zinute: { label: 'Žinutė', type: 'textarea', placeholder: 'Kliento žinutė ar kontekstas' },
    ctaTipas: { label: 'CTA tipas', type: 'select', placeholder: 'Pasirinkite', options: ['Susitikimas', 'Skambutis', 'El. paštas', 'Apžiūra'] },
    siulomaKaina: { label: 'Siūloma kaina (€)', type: 'text', placeholder: '€' },
    kontekstas: { label: 'Kontekstas', type: 'textarea', placeholder: 'Derybų kontekstas' },
    derybuTikslas: { label: 'Derybų tikslas', type: 'select', placeholder: 'Pasirinkite', options: ['Ginti kainą', 'Kompromisas', 'Uždaryti sandorį'] },
    tema: { label: 'Tema', type: 'text', placeholder: 'Rinkos tema' },
    turinioTipas: { label: 'Turinio tipas', type: 'select', placeholder: 'Pasirinkite', options: ['Ekspertinis', 'Apžvalga', 'Prognozė'] },
  },
  theme: {
    light: {
      '--primary': '#1B2A4A',
      '--primary-hover': '#152238',
      '--primary-light': '#2A4A7A',
      '--accent-gold': '#E83E5E',
      '--accent-gold-hover': '#D13350',
      '--surface-0': '#F7F8FA',
      '--surface-1': '#FFFFFF',
      '--text': '#1A1E2C',
      '--text-light': '#6B7280',
      '--border': '#E5E7EB',
      '--output-bg': '#1B2A4A',
      '--success': '#0d9488',
      '--error': '#dc2626',
      '--error-bg': '#fef2f2',
      '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
      '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)',
      '--shadow-lg': '0 25px 50px -12px rgba(0,0,0,0.25)',
    },
    dark: {
      '--primary': '#F06580',
      '--primary-hover': '#E84D6A',
      '--primary-light': '#F58DA5',
      '--accent-gold': '#E83E5E',
      '--accent-gold-hover': '#F06580',
      '--surface-0': '#0F1117',
      '--surface-1': '#1A1D27',
      '--text': '#F0F2F5',
      '--text-light': '#9CA3AF',
      '--border': '#2D3340',
      '--output-bg': '#152238',
      '--success': '#2dd4bf',
      '--error': '#f87171',
      '--error-bg': '#450a0a',
      '--shadow-sm': '0 1px 3px 0 rgba(0,0,0,0.2)',
      '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.2), 0 2px 4px -2px rgba(0,0,0,0.15)',
      '--shadow-lg': '0 25px 50px -12px rgba(0,0,0,0.4)',
    },
  },
  colors: {
    charcoal: '#0F1117',
    navy: '#1B2A4A',
    navyHover: '#152238',
    navyLight: '#2A4A7A',
    coral: '#E83E5E',
    coralHover: '#D13350',
    coralLight: '#F06580',
    gray: '#6B7280',
    textPrimary: '#F0F2F5',
    textSecondary: '#9CA3AF',
    backgroundLight: '#F7F8FA',
    textDark: '#1A1E2C',
    panelsLight: '#FFFFFF',
    border: '#E5E7EB',
  },
  cta: {
    primary: { background: '#E83E5E', text: '#FFFFFF', hoverBackground: '#D13350' },
    secondary: { border: '#1B2A4A', text: '#1B2A4A' },
    accent: { background: '#E83E5E', hoverBackground: '#D13350' },
  },
  libraryPrompts: [
    {
      id: 'skelbimas_nt',
      title: 'NT skelbimo šablonas',
      desc: 'Portalams ir socialiniams kanalams',
      icon: 'sparkles',
      prompt: 'Rolė: NT rinkos analitikas ir aukščiausio lygio NT brokeris (15m patirtis).\nGoal: Sukurti skelbimą pagal objekto duomenis – emocinis arba racionalus kampas.\nTone: premium\nINPUT: Objektas, lokacija, kaina, plotas/kambariai, privalumai, auditorija.\nREASONING: Analizuok objekto vertę, identifikuok auditorijos motyvaciją, suformuok stipriausią pardavimo kampą.\nOUTPUT: Hook, pagrindinis tekstas, 3-5 USP, emocinis argumentas, CTA.\nQUALITY: Tiksli lietuvių kalba, jokio salesy triukšmo, maksimalus įtraukimas.',
    },
    {
      id: 'komunikacija_pirkėjas',
      title: 'Klientų komunikacija',
      desc: 'Atsakymai pirkėjams ir pardavėjams',
      icon: 'message-square',
      prompt: 'Rolė: NT brokerio asistentas. Parengti atsakymą klientui (pirkėjas/pardavėjas) pagal situaciją.\nSituacijos: domisi kaina, neatsako, follow-up po apžiūros, pasiūlymo teikimas.\nOUTPUT: Trumpas, profesionalus atsakymas – vertė, aiškumas, CTA (susitikimas/skambutis).\nTone: pagal kontekstą (premium/profesionalus/draugiškas). Tiksli lietuvių kalba.',
    },
    {
      id: 'derybu_strategija',
      title: 'Derybų argumentacija',
      desc: 'Tikslas, kainos, kontekstas',
      icon: 'handshake',
      prompt: 'Rolė: NT derybų strategas. Suformuoti argumentaciją tikslui: ginti kainą / ieškoti kompromiso / uždaryti sandorį.\nINPUT: Pradinė kaina, siūloma kaina, rinkos kontekstas.\nOUTPUT: 3-5 stiprūs argumentai, atsakymai į tipinius prieštaravimus, aiškus siūlomas žingsnis. Tiksli lietuvių kalba, be agresijos.',
    },
    {
      id: 'rinkos_analize',
      title: 'Rinkos analizė / turinys',
      desc: 'Ekspertinis turinys tema',
      icon: 'bar-chart-3',
      prompt: 'Rolė: NT rinkos analitikas. Sukurti ekspertinį turinį (apžvalga, įžvalgos) nurodyta tema.\nINPUT: Tema, turinio tipas (ekspertinis / apžvalga / prognozė).\nOUTPUT: Struktūruotas turinys – faktai, tendencijos, išvados. Tiksli lietuvių kalba, vertė skaitytojui, jokio tuščio marketingo.',
    },
  ],
  rules: [
    { text: 'Profesionali, tiksli lietuvių kalba', icon: 'check-circle' },
    { text: 'Paruošta naudoti per 30–60 sek.', icon: 'check-circle' },
    { text: 'Maksimalus įtraukimas ir aiški vertė', icon: 'check-circle' },
    { text: 'Pritaikyta NT brokerio kasdieniam darbui', icon: 'check-circle' },
  ],
  footerBadges: ['NT brokeris', '5 režimai', 'Skelbimų kūrimas', 'Derybos'],
  aiToolLinks: [
    { label: 'Atidaryti ChatGPT', url: 'https://chat.openai.com/', icon: 'external-link' },
    { label: 'Atidaryti Claude', url: 'https://claude.ai/', icon: 'external-link' },
    { label: 'Atidaryti Gemini', url: 'https://gemini.google.com/', icon: 'external-link' },
  ],
}
